db_stuff = {'mssql': {'account_type_id': 1,
                      'database_type_id': 1,
                      'create_user_query': lambda account_login,
                                                  user_password: f"USE master;\nCREATE LOGIN {account_login} WITH PASSWORD='{user_password}';\n\nALTER SERVER ROLE dbcreator ADD MEMBER {account_login};\nUSE master;\nGRANT CREATE ANY DATABASE TO {account_login};",
                      'edit_user_query': lambda user_login, new_account_login,
                                                new_account_password: f"ALTER LOGIN {user_login} WITH NAME = {new_account_login};\nALTER LOGIN {new_account_login} WITH PASSWORD = '{new_account_password}';"},
            'postgresql': {'account_type_id': 2,
                           'database_type_id': 2,
                           'create_user_query': lambda account_login,
                                                       user_password: f"CREATE USER {account_login} WITH PASSWORD '{user_password}' CREATEDB;",
                           'edit_user_query': lambda user_login, new_account_login,
                                                     new_account_password: f"ALTER USER {user_login} RENAME TO {new_account_login};\nALTER USER {new_account_login} WITH PASSWORD '{new_account_password}';"},
            'mysql': {'account_type_id': 3,
                      'database_type_id': 3,
                      'create_user_query': lambda account_login,
                                                  user_password: f"CREATE USER '{account_login}'@localhost IDENTIFIED BY '{user_password}';",
                      'edit_user_query': lambda user_login, new_account_login,
                                                new_account_password: f"ALTER USER '{user_login}'@'localhost' RENAME TO '{new_account_login}'@'localhost';\nSET PASSWORD FOR '{new_account_login}'@'localhost' = PASSWORD('{new_account_password}');"}}
